[source.crates-io]
replace-with = 'mirror'
[source.mirror]
registry = "sparse+https://mirrors4.tuna.tsinghua.edu.cn/crates.io-index/"
[registries.mirror]
index = "sparse+https://mirrors4.tuna.tsinghua.edu.cn/crates.io-index/"
